### ISSUE TITLE
SFX issues

### ISSUE THREAD

**Issue by Roxis88** [o5k/tetrio-issues#244]
### Describe the bug/issue
Pretty often, the sfx making a hard 'popping' sounds, that pretty hurtful at the ears. 
It might be just me, so sorry if it's the case.

### Reproducing
Just turn on the SFX. I'm using 5% SFX as per now.

### Expected behavior
Having random 'popping' sound when sfx is sounded.

### Your setup
 - **OS and version**: Win 8
 - **Browser and version**: Google Chrome Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by Wirtualnosc** [comment]
I can confirm this started to happen quite often since yesterday or so... Using Opera 67.0.3575.115

**Comment by JuanMa-78** [comment]
Same has happened to me. I'm on Chrome OS and Google Chrome, both version 81.0.4044.103

I've found the issue to go away (or at least be not as noticeable) with really high (<75%) sfx volume

The issue seems to happen with low sfx volume. I use mine at 8%

**Comment by o5k** [comment]
Fixed in next patch!

**Comment by eternal-sorrow** [comment]
I'm experiencing the bug right now.

**Comment by ZaptorZap** [comment]
Huh, now that I see this issue I can say it's been happening OS wide on my end when the CPU starts hitting high levels. I played CSGO with a friend a few days ago and the audio was practically dead, and the same happened with uncapped ultra Tetr.io. It still happens while I listen to vaporwave and grind that 10 pc badge, but it's a little less frequent and it kinda adds to the music, almost like it's being played through a gramophone haha

Perhaps the OS wide issue makes this one invalid? Just raising that idea.
