### ISSUE TITLE
Some UI text is selectable

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#48]
### Description
You can select some UI texts.

### Reproducing
- Go into quick lobby and select text in the center (either countdown or "quick play, good luck!" text).
- When the game starts, select the room title.

### Expected behavior
Such texts shouldn't be selectable.

### Screenshots
![image](https://user-images.githubusercontent.com/6901295/74779242-007cb900-5295-11ea-97eb-4fe6fef143a1.png)
![image](https://user-images.githubusercontent.com/6901295/74779250-05416d00-5295-11ea-870f-54fe5499664d.png)

### Your setup
Arch Linux 5.5.4-arch1-1 on x86_64 PC, both on Opera 66.0.3515.72 and Firefox 73.0

### Additional context
Related to #47

**Comment by o5k** [comment]
Fixed in next patch.

**Comment by o5k** [comment]
![](https://cdn.discordapp.com/attachments/673305614318960671/680561210034487314/unknown.png)
wakey wakey

**Comment by o5k** [comment]
Ok Ok THIS time it's REALLY fixed OK OK

**Comment by Wirtualnosc** [comment]
no it's not fixed >:C in fact I think it's even worse now.
![image](https://user-images.githubusercontent.com/6901295/75479115-ec247480-5996-11ea-8e5d-00c9c2b55e9b.png)
![image](https://user-images.githubusercontent.com/6901295/75479172-f9d9fa00-5996-11ea-8346-575c4a7b39b7.png)
![image](https://user-images.githubusercontent.com/6901295/75479191-00687180-5997-11ea-88a2-f6e3aace9f8c.png)
![image](https://user-images.githubusercontent.com/6901295/75479209-08c0ac80-5997-11ea-958b-610a198e8df0.png)
![image](https://user-images.githubusercontent.com/6901295/75479226-0fe7ba80-5997-11ea-92e8-76c3e79846ca.png)
Got all of those using CTRL+A

**Comment by o5k** [comment]
how??? it does not do this for me at all???
